### ISSUE TITLE
如何移植为纯静态页面？

### ISSUE THREAD

**Issue by Zxis233** [ldcivan/BA_logo#1]
RT，貌似原作者已经很久没有合过PR了，自己想整合副标题的功能进来，但又不想重新用vercel部署一遍。
请问您是如何移植为纯静态页面的呢？

**Comment by YujioNako** [comment]
我是直接将vercel运行出来的index页面以及需要的js、css等其他文件按顺序保存，很暴力的方法ww

**Comment by Zxis233** [comment]
学到了23333
